# Generated by Django 3.1.3 on 2020-11-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainwebsite', '0005_user_draw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.IntegerField(default=0)),
                ('attempt', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.user')),
            ],
        ),
    ]
