# Generated by Django 3.1.3 on 2020-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_auto_20201105_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_on_hold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
