# Generated by Django 3.1.3 on 2020-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_user_money_on_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money_on_hold',
        ),
        migrations.AddField(
            model_name='user',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
