# Generated by Django 3.1.3 on 2020-11-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0004_auto_20201109_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draw',
            field=models.IntegerField(default=0),
        ),
    ]
